import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import { Providers } from "./redux/provider";
import Footer from "./components/Footer/Footer";
import { Toaster } from "react-hot-toast";

const font = Lato({
  display: "swap",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Weston",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Toaster />
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Navbar />

            <div className="flex-grow">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
